services:
  nginx:
    build:
      context: ./nginx
      args:
        ENVIRONMENT: prod
    depends_on:
      - backend
      # Não depende do frontend em produção
    volumes:
      - /etc/letsencrypt/live/monitoramentocmdca.com.br/:/etc/letsencrypt/live/monitoramentocmdca.com.br/:ro
  
  backend:
    env_file:
      - .env.prod