services:
  nginx:
    build:
      context: ./nginx
      args:
        ENVIRONMENT: prod
    depends_on:
      - backend
      # Não depende do frontend em produção
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro

  
  backend:
    env_file:
      - .env.prod