services:
  nginx:
    build: 
      context: ./nginx
      args:
        ENVIRONMENT: prod
    ports:
      - "80:80"
    restart: always
    depends_on:
      # - frontend (será adicionado no override para dev)
      - backend

  

  backend:
    build: ./www
    # A porta agora é acessada apenas pela rede interna do Docker, através do Nginx
    # ports:
    #  - "8080:8080"
    restart: always
    env_file:
      - .env.dev
