services:
  mysql:
    image: mysql:8.0
    container_name: localDB-test
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: propostasDB
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    restart: unless-stopped
